interface User {
  map(arg0: (data: User, index: number) => JSX.Element): React.ReactNode;
  user_id: number;
  emp_id: number;
  role_name: number;
  name: string;
  empname: string;
  username: string;
  email: string;
  gender: string;
  dob: string | number;
  image: string;
  id: number;
  role_id: number;
  status_id: number;
  address: string;
  startYear: string;
  endYear: string;
  phone: string;
  action: string;
  emp_name: string;
  empleave_id: number;
  emptiming_arrivaldate: string | number;
  emptiming_arrivaltime: string | number;
  emptiming_departuredate: string | number;
  emptiming_departuretime: string | number;
  empleave_startdate: string | number;
  empleave_enddate: string | number;
  empleave_totaldays: string | number;
  empleave_comment: string;
  data: [];
  per_page: string | number;
  total: string | number;
  length: string | number;
}
